### PR TITLE
Add cropped RGB image to product counting action

### PR DESCRIPTION
**Pull request by samcaulfield**
Hi there,

Our new product counting system performs counting on RGB images. In order to support this and to maintain backwards-compatibility with the old product counting system, I suggest adding a cropped RGB image to the product counting action specification.

### CODE REVIEW

**Comment by airballking** [comment]
@samcaulfield I suggest to add another field that indicates which image to use for counting. You can have a look at the Marker message and its type field for some inspiration:

https://github.com/ros/common_msgs/blob/jade-devel/visualization_msgs/msg/Marker.msg#L24

**Comment by samcaulfield** [comment]
Hi Georg, if I understand correctly you are suggesting that the goal look something like this:

```
# The cropped image, which may be a depth image or an RGB image depending on the value of isDepthImage.
sensor_msgs/CompressedImage cropped_image

# If true then cropped_image is a depth image. If false then cropped_image is an RGB image.
bool isDepthImage
```

If so, then that works for us and I will make the change.

**Comment by airballking** [comment]
Almost. my suggestion was something along those lines:

```
# constants to encode which image type to expect for counting
uint8 INVALID_TYPE=0
uint8 DEPTH_IMAGE=1
uint8 RGB_IMAGE=2

# field to specify which image type to expect for counting
uint8 image_type

# cropped image to be used for counting
sensor_msgs/CompressedImage cropped_image
```
Like this, you can later introduce further types by just adding more constants without breaking API. However, if you can _guarantee_ that there will never be more than two types, then a bool will suffice.

**Comment by samcaulfield** [comment]
Sorry, I had master checked out when I pushed the change. I'll undo that now and open another PR.

**Pull request merged**
